name: Build

on: [ push, pull_request ]

env:
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, shell: bash }
          - { os: windows-latest, shell: 'msys2 {0}' }
    defaults:
      run:
        shell: ${{ matrix.config.os }}
    steps:
      - name: 'Setup Clang MinGW'
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-clang

      - name: 'Clone Repo'
        uses: actions/checkout@v2

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Build kotlin-intrin'
        run: ./gradlew build --stacktrace

      - name: 'Publish kotlin-intrin'
        run: ./gradlew publish --stacktrace
        if: startsWith(github.ref, 'refs/tags/')
