name: Build

on: [ push, pull_request ]

env:
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build-unix:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Dependencies
        run: |
          case $RUNNER_OS in
            "Linux") 
              sudo apt update
              sudo apt install llvm
            ;;
            "macOS")
              brew install llvm 
            ;;
            *) echo "Unknown OS '$RUNNER_OS'" ;;
          esac

      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build kotlin-intrin
        run: ./gradlew check --stacktrace

      - name: Publish kotlin-intrin
        run: ./gradlew publish --stacktrace
        if: startsWith(github.ref, 'refs/tags/')

  build-windows:
    name: Build
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup Clang MinGW
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-clang

      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build kotlin-intrin
        run: ./gradlew check --stacktrace

      - name: Publish kotlin-intrin
        run: ./gradlew publish --stacktrace
        if: startsWith(github.ref, 'refs/tags/')
