name: Build

on: [ push, pull_request ]

env:
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubunutu-latest, windows-latest ]
    steps:
      - name: 'Install Clang'
        run: choco install llvm
        if: matrix.os == 'windows-latest'

      - name: 'Clone Repo'
        uses: actions/checkout@v1

      - name: 'Build kotlin-intrin'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'build --stacktrace'

      - name: 'Publish kotlin-intrin'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'publish --stacktrace'
        if: startsWith(github.ref, 'refs/tags/')
